### ISSUE TITLE
 server crashing after Retrying in 1 second.

### ISSUE THREAD

**Issue by tmibvishal** [vishalBindal/vehicle-routing#6]
```
$ gunicorn vrp_api -b :16000 --reload
[2020-04-30 21:33:30 +0530] [5493] [INFO] Starting gunicorn 20.0.4
[2020-04-30 21:33:30 +0530] [5493] [ERROR] Connection in use: ('', 16000)
[2020-04-30 21:33:30 +0530] [5493] [ERROR] Retrying in 1 second.
```

Then the server closes
I have no idea what this is, please fix this.

**Comment by vishalBindal** [comment]
This is due to the previous connection to port 16000 not closing properly. You can change the port in the command line instruction as well as in the main.js file to resolve this. Probably we should work on some other solution.

**Comment by tmibvishal** [comment]
Use this to check the running ports
`$ ps -ax |grep gunicorn`

``` bash
1558 ??         0:05.96 /Users/vishal/.pyenv/versions/3.6.0/bin/python3.6 /Users/vishal/.pyenv/versions/3.6.0/bin/gunicorn vrp_api -b :16000 --reload
```

Then locate the process if and close it

`$ kill 1558`
